### ISSUE TITLE
Invalid DN

### ISSUE THREAD

**Issue by BinkyWong** [dthree/addict#23]
Hi,

I'm using:

`addict --url ldaps://192.168.x.x --user xxxxx@xxxxxx.com --pass xxxxxxxxxxx`

But I'm getting

`{ InvalidDnSyntaxError: invalid DN
    at messageCallback (/home/binky/.nvm/versions/node/v9.7.1/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/home/binky/.nvm/versions/node/v9.7.1/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1089:14)
    at Parser.emit (events.js:127:13)
    at Parser.write (/home/binky/.nvm/versions/node/v9.7.1/lib/node_modules/addict/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at TLSSocket.onData (/home/binky/.nvm/versions/node/v9.7.1/lib/node_modules/addict/node_modules/ldapjs/lib/client/client.js:1076:22)
    at TLSSocket.emit (events.js:127:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at TLSSocket.Readable.push (_stream_readable.js:213:10)
    at TLSWrap.onread (net.js:598:20) lde_message: 'invalid DN', lde_dn: null }
`

what do I need to ensure a "valid" DN? Sorry if this is a completely n00b question, it is because I am a n00b :) Anyone got any pointers? 

Thanks!

**Comment by fei0x** [comment]
Have you got it working with regular ldap yet? if not then I think you might have the wrong version of node installed? (though I'm a bit of a n00b at this too.)
These are the steps i ran on a blank ubuntu 16.04 to get it working with regular ldap:

sudo apt-get install npm
sudo apt install nodejs-legacy
sudo apt-get install nodejs
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash

LOGOUT
LOGIN

nvm install 8.9.4
sudo npm i addict -g
addict --url ldap:// . . . 

for LDAPS i know you need to enable LDAPS in AD before it works, but I never figured out how myself.

**Comment by BinkyWong** [comment]
Thanks for the tip, unfortunately still does not work, so I'm probably doing something badly wrong

RE: SSL, you can enable it like this:

Create the certificates:

`openssl req -config /etc/pki/tls/openssl.cnf -new -x509 -extensions v3_ca -keyout /etc/openldap/certs/ca.key -out /etc/openldap/certs/ca.crt -days 3650`
`openssl req -new -x509 -nodes -out /etc/openldap/certs/ldap.mysite.com.pem -keyout /etc/openldap/certs/ldap.mysite.com.key.pem -days 720 -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=ldap.mysite.com"`

Edit ldap.conf and add the following at the bottom:

`TLSCACertificateFile /etc/openldap/certs/ca.crt`
`TLSCertificateFile /etc/openldap/certs/ldap.mysite.com.pem`
`TLSCertificateKeyFile /etc/openldap/certs/ldap.mysite.com.key.pem`
 
then

`slaptest` to ensure the config parses OK

and 

`systemctl restart slapd`

to restart and it should work - I've tested under Centos 7, hope this helps!

**Comment by zzswang** [comment]
I have same problem.

I start dockers with docker-compose with following containers:

```
  ldap:
    restart: always
    image: osixia/openldap
    environment:
      - LDAP_ORGANISATION=36node
      - LDAP_DOMAIN=36node.com
      - LDAP_ADMIN_PASSWORD=mypassword
    ports:
      - 389:389
      - 636:636

  addict:
    restart: always
    image: dthree/addict
    environment:
      - ADDICT_URL=ldap://ldap-host
      - ADDICT_USER=admin@36node.com
      - ADDICT_PASS=mypassword
    links:
      - ldap:ldap-host
    ports:
      - 3000:3000

  phpldapadmin:
    restart: always
    image: osixia/phpldapadmin
    links:
      - ldap:ldap-host
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - 8889:80
```

phpldapadmin works, but addict keep saying invalid DN
